GATE_WS_URL = "wss://fx-ws.gateio.ws/v4/ws/usdt"
GATE_API_URL = "https://api.gateio.ws/api/v4"

HYPERLIQUID_API_URL = "https://api.hyperliquid.xyz"
HYPERLIQUID_WS_URL = "wss://api.hyperliquid.xyz/ws"

GATE_FEE_TAKER = 0.0005
GATE_FEE_MAKER = 0.0002
HYPERLIQUID_FEE_TAKER = 0.00025
HYPERLIQUID_FEE_MAKER = 0.0001

MAX_RETRIES = 3
RETRY_DELAY_SECONDS = 2.0
BACKOFF_MULTIPLIER = 2.0

WS_PING_INTERVAL_SECONDS = 20
WS_RECONNECT_DELAY_SECONDS = 5